### ISSUE TITLE
Issue while trying to install reaction menu

### ISSUE THREAD

**Issue by TimBritcliffe** [Defxult/reactionmenu#42]
**Description**
I am trying to install reactionmenu for a new project but for some reason it doesn't work

I use "pip install reactionmenu" as it worked for me in the past and it starts installing. The issue is that after a bit of time it stops installing and gives the following error:

```PS C:\Users\Human\Documents\TestBot> pip install reactionmenu
Collecting reactionmenu
  Using cached reactionmenu-3.1.1.tar.gz (74 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Human\AppData\Local\Temp\pip-install-9iwql_ju\reactionmenu_66ee8a68aeda4f62bf68a694e643d1c2\setup.py", line 3, in <module>
          from reactionmenu import __source__
        File "C:\Users\Human\AppData\Local\Temp\pip-install-9iwql_ju\reactionmenu_66ee8a68aeda4f62bf68a694e643d1c2\reactionmenu\__init__.py", line 12, in <module>
          from .buttons import ReactionButton, ViewButton
        File "C:\Users\Human\AppData\Local\Temp\pip-install-9iwql_ju\reactionmenu_66ee8a68aeda4f62bf68a694e643d1c2\reactionmenu\buttons.py", line 51, in <module>
          from .abc import _BaseButton, PaginationEmojis
        File "C:\Users\Human\AppData\Local\Temp\pip-install-9iwql_ju\reactionmenu_66ee8a68aeda4f62bf68a694e643d1c2\reactionmenu\abc.py", line 61, in <module>
          from typing_extensions import Self
      ModuleNotFoundError: No module named 'typing_extensions'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.```

**Comment by Defxult** [comment]
This should be fixed as of v3.1.2 (just released an update to PyPI). If the problem persists, please open another issue.

Thanks!
