### ISSUE TITLE
Going back to a previous page with local file paramater sends an interaction error

### ISSUE THREAD

**Issue by Dynamixus** [Defxult/reactionmenu#50]
### Describe the bug

Followed the instructions here to use a local file as thumbnail in my code:
https://github.com/Defxult/reactionmenu/issues/46

It works, but going to the next page and then back to the page with the local file thumbnail sends an interaction error, saying `No such *file* found`.

### Minimal Reproducible Code

```python
@commands.hybrid_command(
  name = "weap",
  description = "Information on specified weapon.")
  @app_commands.describe(weapon="The weapon you want to know more of.")

@checks.not_blacklisted()
async def weap(self, context: Context, weapon: str) -> None:

  await context.defer()

  menu = ViewMenu(context, menu_type = ViewMenu.TypeEmbed, disable_items_on_timeout = False, remove_items_on_timeout = True, timeout = 600.0)

  mainpage = discord.Embed(
    title = f"{weapDetails['rarity']} {weapDetails['name']} {weapons[weapDetails['type']]}",
    description = f"{weapDetails['description']}",
    color = colors[weapDetails['type']],
    timestamp = datetime.now(),
    )

  imgpath = "./assets/weapons"
  imgdirlist = listdir(imgpath)
  img_weap = f"{img_weap}.png"
  if img_weap in imgdirlist:
    f = discord.File(f"./assets/weapons/{img_weap}", filename=img_weap)
    mainpage.set_thumbnail(url=f"attachment://{img_weap}")
    menu.add_page(embed=mainpage, files=[f])
  else:
    menu.add_page(embed=mainpage)

  menu.add_button(ViewButton(style=discord.ButtonStyle.primary, emoji='⏮️', label='Previous', custom_id = ViewButton.ID_PREVIOUS_PAGE))	
  menu.add_button(ViewButton(style=discord.ButtonStyle.primary, emoji='⏭️', label='Next', custom_id = ViewButton.ID_NEXT_PAGE))
  menu.add_button(ViewButton(style=discord.ButtonStyle.danger, label = "Close", custom_id = ViewButton.ID_END_SESSION))

  await menu.start()
```

### Traceback

```txt
Task exception was never retrieved
future: <Task finished name='discord-ui-view-dispatch-c45b2e8a0ed37f2a2f7baecb790e50eb' coro=<View._scheduled_task() done, defined at C:\Users\Xer\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ui\view.py:416> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "C:\Users\Xer\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ui\view.py", line 429, in _scheduled_task
    return await self.on_error(interaction, e, item)
  File "C:\Users\Xer\AppData\Local\Programs\Python\Python310\lib\site-packages\reactionmenu\views_menu.py", line 285, in _on_dpy_view_error
    raise error
  File "C:\Users\Xer\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "C:\Users\Xer\AppData\Local\Programs\Python\Python310\lib\site-packages\reactionmenu\buttons.py", line 148, in callback
    await self._menu._paginate(self, interaction) # type: ignore
  File "C:\Users\Xer\AppData\Local\Programs\Python\Python310\lib\site-packages\reactionmenu\views_menu.py", line 1099, in _paginate
    await inter.response.edit_message(**self._determine_kwargs(self._pc.prev()))
  File "C:\Users\Xer\AppData\Local\Programs\Python\Python310\lib\site-packages\reactionmenu\abc.py", line 799, in _determine_kwargs
    maybe_new_files = [discord.File(f.filename) for f in page.files] if page.files else [] # type: ignore
  File "C:\Users\Xer\AppData\Local\Programs\Python\Python310\lib\site-packages\reactionmenu\abc.py", line 799, in <listcomp>
    maybe_new_files = [discord.File(f.filename) for f in page.files] if page.files else [] # type: ignore
  File "C:\Users\Xer\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\file.py", line 97, in __init__
    self.fp = open(fp, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'rust.png'
```

### Library Version

- Python v3.10.0-final
- discord.py v2.3.1-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19044

### Required Checklist

- [X] I am using discord.py 2.0 or higher
- [X] I am using reactionmenu 3.1.0 or higher
- [X] I have the required [intents](https://github.com/Defxult/reactionmenu#intents) enabled

**Comment by Defxult** [comment]
This can't be replicated.
```py
    @commands.hybrid_command(name = "test", description = "...")
    async def test(self, context) -> None:
        await context.defer()

        menu = ViewMenu(context, menu_type = ViewMenu.TypeEmbed, disable_items_on_timeout = False, remove_items_on_timeout = True, timeout = 600.0)
        mainpage = discord.Embed(title = "1")

        f = discord.File("./venom.jpeg", filename="venom.jpeg")
        mainpage.set_thumbnail(url="attachment://venom.jpeg")

        menu.add_page(mainpage, files=[f])
        menu.add_page(discord.Embed(title="Hello"))

        menu.add_button(ViewButton(style=discord.ButtonStyle.primary, emoji='⏮️', label='Previous', custom_id = ViewButton.ID_PREVIOUS_PAGE))	
        menu.add_button(ViewButton(style=discord.ButtonStyle.primary, emoji='⏭️', label='Next', custom_id = ViewButton.ID_NEXT_PAGE))
        menu.add_button(ViewButton(style=discord.ButtonStyle.danger, label = "Close", custom_id = ViewButton.ID_END_SESSION))

        await menu.start()
```
Result

https://github.com/Defxult/reactionmenu/assets/52070034/51d62636-c816-4b58-8a24-c9e97826620a
