### ISSUE TITLE
DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.

### ISSUE THREAD

**Issue by TruncatedDinosour** [Defxult/reactionmenu#51]
### Describe the bug

when using the library i get

```py
DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
```

u should remove usage of it

### Minimal Reproducible Code

```python
*no*
```

### Traceback

```txt
Exception in callback ReactionMenu._session_done_callback(<Task finishe...ython 3.11.')>)
handle: <Handle ReactionMenu._session_done_callback(<Task finishe...ython 3.11.')>)>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ari/124/venv/lib/python3.9/site-packages/reactionmenu/core.py", line 234, in _session_done_callback
    task.result() # this is needed to raise ANY exception that occurred during the pagination process
  File "/home/ari/124/venv/lib/python3.9/site-packages/reactionmenu/core.py", line 450, in __paginate
    done, pending = await asyncio.wait(wait_for_aws, return_when=asyncio.FIRST_COMPLETED)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 406, in wait
    warnings.warn("The explicit passing of coroutine objects to "
DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal
in Python 3.11.
```

### Library Version

- Python v3.9.2-final
- discord.py v2.3.1-final
- aiohttp v3.8.5
- system info: Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21)

### Required Checklist

- [X] I am using discord.py 2.0 or higher
- [X] I am using reactionmenu 3.1.0 or higher
- [X] I have the required [intents](https://github.com/Defxult/reactionmenu#intents) enabled

**Comment by Defxult** [comment]
Fixed. Thank you!
