### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by arianx55678** [Defxult/reactionmenu#52]
### Describe the bug

i just ran the code and it shows below :
i have another command and all of them work
by the way im new to Python for a week
thanks for your help!!!!

### Minimal Reproducible Code

```python
@bot.command()
async def abc(ctx: commands.Context):
    menu = ViewMenu(ctx, menu_type=ViewMenu.TypeEmbed)
    
    f = discord.File("image.png", filename="image.png")
    embed = discord.Embed(title="With local image")
    embed.set_thumbnail(url="attachment://image.png")
    embed.set_footer(text=f"Requested by {ctx.author}", icon_url = ctx.author.avatar.url)

    menu.add_page(embed, files=[f])
    menu.add_page(discord.Embed(title="Hello"))
    menu.add_buttons([ViewMenu.back(), ViewMenu.next()])
    
    await menu.start()
```

### Traceback

```txt
ERROR    discord.ext.commands.bot Ignoring exception in command abc
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dory/Downloads/dcbot確認上傳/kaiMAIN.py", line 35, in abc
    menu.add_buttons([ViewMenu.back(), ViewMenu.next()])
                      ^^^^^^^^^^^^^
AttributeError: type object 'ViewMenu' has no attribute 'back'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: type object 'ViewMenu' has no attribute 'back'
```

### Library Version

- Python v3.11.5-final
- discord.py v2.3.2-final
- system MacOS

### Required Checklist

- [X] I am using discord.py 2.0 or higher
- [X] I am using reactionmenu 3.1.0 or higher
- [X] I have the required [intents](https://github.com/Defxult/reactionmenu#intents) enabled

**Comment by Defxult** [comment]
It's `ViewButton.back()`, not `ViewMenu.back()`
